In [14]:
import pandas as pd

df_nfhs = pd.read_csv("nfhs_survey.csv")

print(df_nfhs.shape)
df_nfhs.head()

(4819, 9)

,S.No.,indicator code,Indicators,sub indicators,NFHS-5 (2019-20),Unnamed: 5,Unnamed: 6,NFHS-4 2015-16,STATE/UT
0,NaN,NaN,NaN,NaN,Urban,Rural,Total,Total,NaN
1,1.0,1.0,Population and Household Profile,Female population age 6 years and above who ev...,86.5,81.8,83.5,84.7,Andaman & Nicobar Islands
2,2.0,2.0,Population and Household Profile,Population below age 15 years (%),22.7,19.7,20.8,23.9,Andaman & Nicobar Islands
3,3.0,3.0,Population and Household Profile,Sex ratio of the total population (females per...,1023,929,963,977,Andaman & Nicobar Islands
4,4.0,4.0,Population and Household Profile,Sex ratio at birth for children born in the la...,941,891,914,859,Andaman & Nicobar Islands

In [15]:
print(df_nfhs.columns.tolist())

['S.No.', 'indicator code', 'Indicators', ' sub indicators', 'NFHS-5 (2019-20)', 'Unnamed: 5', 'Unnamed: 6', 'NFHS-4 2015-16', 'STATE/UT']

In [16]:
df_nfhs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4819 entries, 0 to 4818
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   S.No.             4818 non-null   float64
 1   indicator code    4818 non-null   float64
 2   Indicators        4818 non-null   object
 3    sub indicators   4818 non-null   object
 4   NFHS-5 (2019-20)  4819 non-null   object
 5   Unnamed: 5        4685 non-null   object
 6   Unnamed: 6        4819 non-null   object
 7   NFHS-4 2015-16    4819 non-null   object
 8   STATE/UT          4818 non-null   object
dtypes: float64(2), object(7)
memory usage: 339.0+ KB

In [17]:
keywords = [
    "violence",
    "physical",
    "sexual",
    "emotional",
    "husband",
    "partner",
    "injury",
    "control",
    "help",
    "alcohol",
    "spousal"
]

mask = df_nfhs["Indicators"].astype(str).str.contains(
    "|".join(keywords),
    case=False,
    na=False
) | df_nfhs[" sub indicators"].astype(str).str.contains(
    "|".join(keywords),
    case=False,
    na=False
)

nfhs_relevant = df_nfhs[mask]

print(nfhs_relevant.shape)
nfhs_relevant[
    ["Indicators", " sub indicators", "NFHS-5 (2019-20)", "STATE/UT"]
].to_string(index=False)

(407, 9)

'                                                               Indicators                                                                                                                          sub indicators NFHS-5 (2019-20)                             STATE/UT\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             19.6            Andaman & Nicobar Islands\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             19.4            Andaman & Nicobar Islands\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             23.4            Andaman & Nicobar Islands\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             28.2            Andaman & Nicobar Islands\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             23.2            Andaman & Nicobar Islands\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)            (0.0)            Andaman & Nicobar Islands\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              1.4            Andaman & Nicobar Islands\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)             15.0            Andaman & Nicobar Islands\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             44.7            Andaman & Nicobar Islands\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              0.7            Andaman & Nicobar Islands\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             33.8            Andaman & Nicobar Islands\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             23.2                       Andhra Pradesh\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             24.9                       Andhra Pradesh\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             27.5                       Andhra Pradesh\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             32.2                       Andhra Pradesh\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             28.8                       Andhra Pradesh\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              3.5                       Andhra Pradesh\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              3.8                       Andhra Pradesh\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)              1.9                       Andhra Pradesh\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             15.8                       Andhra Pradesh\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              0.3                       Andhra Pradesh\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             20.5                       Andhra Pradesh\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             16.6                                Assam\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             20.4                                Assam\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             22.5                                Assam\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             23.8                                Assam\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             26.6                                Assam\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              2.2                                Assam\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              7.4                                Assam\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)             16.2                                Assam\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             43.9                                Assam\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              2.6                                Assam\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             21.3                                Assam\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             16.3                                Bihar\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             20.3                                Bihar\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             16.6                                Bihar\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             19.5                                Bihar\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             40.6                                Bihar\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              1.9                                Bihar\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              7.1                                Bihar\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)              3.6                                Bihar\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             40.3                                Bihar\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              0.5                                Bihar\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             14.0                                Bihar\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             14.0 Dadra & Nagar Haveli and Daman & Diu\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             17.2 Dadra & Nagar Haveli and Daman & Diu\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             16.5 Dadra & Nagar Haveli and Daman & Diu\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             17.0 Dadra & Nagar Haveli and Daman & Diu\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             21.8 Dadra & Nagar Haveli and Daman & Diu\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              1.3 Dadra & Nagar Haveli and Daman & Diu\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              4.4 Dadra & Nagar Haveli and Daman & Diu\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)              2.4 Dadra & Nagar Haveli and Daman & Diu\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             39.6 Dadra & Nagar Haveli and Daman & Diu\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              0.5 Dadra & Nagar Haveli and Daman & Diu\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             29.1 Dadra & Nagar Haveli and Daman & Diu\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             20.6                                  Goa\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             23.0                                  Goa\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             27.6                                  Goa\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             25.9                                  Goa\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)              6.0                                  Goa\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              0.9                                  Goa\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              1.6                                  Goa\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)              2.4                                  Goa\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                              Men age 15 years and above who use any kind of tobacco (%)             19.5                                  Goa\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                    Women age 15 years and above who consume alcohol (%)              5.6                                  Goa\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                                      Men age 15 years and above who consume alcohol (%)             38.2                                  Goa\n          Blood Sugar Level among Adults (age 15 years and above) - Women                          Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Women             17.6                              Gujarat\n            Blood Sugar Level among Adults (age 15 years and above) - Men                            Blood sugar level - high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%) - Men             17.8                              Gujarat\n               Hypertension among Adults (age 15 years and above) - Women Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Women             21.1                              Gujarat\n                 Hypertension among Adults (age 15 years and above) - Men   Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%) - Men             20.3                              Gujarat\n                                  Gender Based Violence (age 18-49 years)                                                       Ever-married women age 18-49 years who have ever experienced spousal violence (%)             10.0                              Gujarat\n                                  Gender Based Violence (age 18-49 years)                                      Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)              2.2                              Gujarat\n                                  Gender Based Violence (age 18-49 years)                                                                  Young women age 18-29 years who experienced sexual violence by age (%)              3.0                              Gujarat\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                                            Women age 15 years and above who use any kind of tobacco (%)              5.4                              Gujarat\nTobacco Use and Alcohol Consumption among Adults (age 15 years and above)                                                   

In [18]:
# Keep only relevant violence/risk indicators
risk_indicators = df_nfhs[
    df_nfhs["Indicators"].astype(str).str.contains(
        "Gender Based Violence|Tobacco Use and Alcohol",
        case=False,
        na=False
    )
].copy()

risk_indicators[
    ["Indicators", " sub indicators", "NFHS-5 (2019-20)", "STATE/UT"]
].head(30)

,Indicators,sub indicators,NFHS-5 (2019-20),STATE/UT
122,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ev...,23.2,Andaman & Nicobar Islands
123,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ex...,(0.0),Andaman & Nicobar Islands
124,Gender Based Violence (age 18-49 years),Young women age 18-29 years who experienced se...,1.4,Andaman & Nicobar Islands
125,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who use any kind ...,15.0,Andaman & Nicobar Islands
126,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who use any kind of...,44.7,Andaman & Nicobar Islands
127,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who consume alcoh...,0.7,Andaman & Nicobar Islands
128,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who consume alcohol...,33.8,Andaman & Nicobar Islands
253,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ev...,28.8,Andhra Pradesh
254,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ex...,3.5,Andhra Pradesh
255,Gender Based Violence (age 18-49 years),Young women age 18-29 years who experienced se...,3.8,Andhra Pradesh
256,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who use any kind ...,1.9,Andhra Pradesh
257,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who use any kind of...,15.8,Andhra Pradesh
258,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who consume alcoh...,0.3,Andhra Pradesh
259,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who consume alcohol...,20.5,Andhra Pradesh
384,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ev...,26.6,Assam
385,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ex...,2.2,Assam
386,Gender Based Violence (age 18-49 years),Young women age 18-29 years who experienced se...,7.4,Assam
387,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who use any kind ...,16.2,Assam
388,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who use any kind of...,43.9,Assam
389,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who consume alcoh...,2.6,Assam
390,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who consume alcohol...,21.3,Assam
515,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ev...,40.6,Bihar
516,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ex...,1.9,Bihar
517,Gender Based Violence (age 18-49 years),Young women age 18-29 years who experienced se...,7.1,Bihar
518,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who use any kind ...,3.6,Bihar
519,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who use any kind of...,40.3,Bihar
520,Tobacco Use and Alcohol Consumption among Adul...,Women age 15 years and above who consume alcoh...,0.5,Bihar
521,Tobacco Use and Alcohol Consumption among Adul...,Men age 15 years and above who consume alcohol...,14.0,Bihar
642,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ev...,21.8,Dadra & Nagar Haveli and Daman & Diu
643,Gender Based Violence (age 18-49 years),Ever-married women age 18-49 years who have ex...,1.3,Dadra & Nagar Haveli and Daman & Diu

In [20]:
violence = df_nfhs[
    df_nfhs[" sub indicators"].astype(str).str.contains(
        "spousal violence|physical violence during any pregnancy|sexual violence",
        case=False,
        na=False
    )
].copy()

violence[
    ["sub indicators", "NFHS-5 (2019-20)", "STATE/UT"]
]

KeyError: "['sub indicators'] not in index"